server:
  port: 8072

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      # FIXED: Looks for the EUREKA_SERVER_URL variable first, fallback to container name second
      defaultZone: "${EUREKA_SERVER_URL:http://eurekaserver-rest-api:8070/eureka/}"

